import rtconfig

import os
Import('rtconfig')
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()

src = Glob('*.c')

src = src + Glob('./foc/*.c')
src = src + Glob('./current_calibration/*.c')
src = src + Glob('./electrical_angle_calibration/*.c')

CPPDEFINES=[]
CPPPATH = [cwd]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')







