from building import *

cwd = GetCurrentDir()

# add the general drivers
src = Split("""
    board.c
    rtt_board.c
    pinmux.c
    fal_flash_port.c
    drv_gc9a01.c
    drv_AS5600.c
    pwm_init.c
    adc_init.c
    
""")

CPPPATH = [cwd]
CPPDEFINES=['D25', 'HPM5361']

group = DefineGroup('Board', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
