################################################################################
# 自动生成的文件。不要编辑！
################################################################################

-include ../makefile.init

RM := rm -rf

# All of the sources participating in the build are defined here
-include sources.mk
-include startup/HPM5361/toolchains/gcc/subdir.mk
-include startup/HPM5361/subdir.mk
-include rt-thread/src/subdir.mk
-include rt-thread/libcpu/risc-v/common/subdir.mk
-include rt-thread/components/libc/compilers/newlib/subdir.mk
-include rt-thread/components/libc/compilers/common/subdir.mk
-include rt-thread/components/finsh/subdir.mk
-include rt-thread/components/drivers/spi/subdir.mk
-include rt-thread/components/drivers/serial/subdir.mk
-include rt-thread/components/drivers/misc/subdir.mk
-include rt-thread/components/drivers/ipc/subdir.mk
-include rt-thread/components/drivers/i2c/subdir.mk
-include rt-thread/components/drivers/hwtimer/subdir.mk
-include rt-thread/components/drivers/core/subdir.mk
-include packages/LVGL-v8.3.11/src/widgets/subdir.mk
-include packages/LVGL-v8.3.11/src/misc/subdir.mk
-include packages/LVGL-v8.3.11/src/hal/subdir.mk
-include packages/LVGL-v8.3.11/src/font/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/win/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/tileview/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/tabview/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/spinner/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/spinbox/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/span/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/msgbox/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/meter/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/menu/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/list/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/led/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/keyboard/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/imgbtn/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/colorwheel/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/chart/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/calendar/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/animimg/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/themes/mono/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/themes/default/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/themes/basic/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/others/snapshot/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/others/msg/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/others/monkey/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/others/imgfont/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/others/ime/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/others/gridnav/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/others/fragment/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/tiny_ttf/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/sjpg/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/rlottie/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/qrcode/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/png/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/gif/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/fsdrv/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/freetype/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/ffmpeg/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/bmp/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/layouts/grid/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/layouts/flex/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/subdir.mk
-include packages/LVGL-v8.3.11/src/draw/swm341_dma2d/subdir.mk
-include packages/LVGL-v8.3.11/src/draw/sw/subdir.mk
-include packages/LVGL-v8.3.11/src/draw/stm32_dma2d/subdir.mk
-include packages/LVGL-v8.3.11/src/draw/sdl/subdir.mk
-include packages/LVGL-v8.3.11/src/draw/renesas/subdir.mk
-include packages/LVGL-v8.3.11/src/draw/nxp/vglite/subdir.mk
-include packages/LVGL-v8.3.11/src/draw/nxp/pxp/subdir.mk
-include packages/LVGL-v8.3.11/src/draw/arm2d/subdir.mk
-include packages/LVGL-v8.3.11/src/draw/subdir.mk
-include packages/LVGL-v8.3.11/src/core/subdir.mk
-include packages/LVGL-v8.3.11/env_support/rt-thread/subdir.mk
-include libraries/misc/rtt_os_tick/subdir.mk
-include libraries/misc/rtt_interrupt_util/subdir.mk
-include libraries/hpm_sdk/soc/HPM5300/HPM5361/boot/subdir.mk
-include libraries/hpm_sdk/soc/HPM5300/HPM5361/subdir.mk
-include libraries/hpm_sdk/drivers/src/subdir.mk
-include libraries/hpm_sdk/components/dma_mgr/subdir.mk
-include libraries/hpm_sdk/components/debug_console/subdir.mk
-include libraries/drivers/subdir.mk
-include build/kernel/src/subdir.mk
-include build/kernel/libcpu/risc-v/common/subdir.mk
-include build/kernel/components/libc/compilers/newlib/subdir.mk
-include build/kernel/components/libc/compilers/common/subdir.mk
-include build/kernel/components/finsh/subdir.mk
-include build/kernel/components/drivers/spi/subdir.mk
-include build/kernel/components/drivers/serial/subdir.mk
-include build/kernel/components/drivers/misc/subdir.mk
-include build/kernel/components/drivers/ipc/subdir.mk
-include build/kernel/components/drivers/i2c/subdir.mk
-include build/kernel/components/drivers/hwtimer/subdir.mk
-include build/kernel/components/drivers/core/subdir.mk
-include build/board/subdir.mk
-include build/applications/foc/subdir.mk
-include build/applications/electrical_angle_calibration/subdir.mk
-include build/applications/current_calibration/subdir.mk
-include build/applications/subdir.mk
-include board/subdir.mk
-include applications/foc/subdir.mk
-include applications/electrical_angle_calibration/subdir.mk
-include applications/current_calibration/subdir.mk
-include applications/subdir.mk
-include subdir.mk
-include objects.mk

ifneq ($(MAKECMDGOALS),clean)
ifneq ($(strip $(ASM_DEPS)),)
-include $(ASM_DEPS)
endif
ifneq ($(strip $(S_DEPS)),)
-include $(S_DEPS)
endif
ifneq ($(strip $(S_UPPER_DEPS)),)
-include $(S_UPPER_DEPS)
endif
ifneq ($(strip $(C_DEPS)),)
-include $(C_DEPS)
endif
endif

-include ../makefile.defs

# Add inputs and outputs from these tool invocations to the build variables 
SECONDARY_FLASH += \
rtthread.bin \

SECONDARY_LIST += \
rtthread.lst \

SECONDARY_SIZE += \
rtthread.siz \


# 所有目标
all: rtthread.elf secondary-outputs

# 工具调用
rtthread.elf: $(OBJS) $(USER_OBJS)
	riscv32-unknown-elf-gcc -march=rv32imac -mabi=ilp32 -msmall-data-limit=8 -mno-strict-align -mno-save-restore -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections  -g3 -gdwarf-2 -T "D:\workTools\RT-ThreadStudio\workspace\HPM5300EVK_DEMO\board\linker_scripts\flash_rtt.ld" -Xlinker --gc-sections -Xlinker -print-memory-usage -Wl,-Map,"rtthread.map" --specs=nano.specs -u _printf_float -u _scanf_float --specs=nosys.specs -nostartfiles -Wl,--gc-sections -Wl,-cref,-Map=rtthread.map -mcmodel=medlow -o "rtthread.elf" $(OBJS) $(USER_OBJS) $(LIBS)

rtthread.bin: rtthread.elf
	riscv32-unknown-elf-objcopy -O binary "rtthread.elf"  "rtthread.bin"

rtthread.lst: rtthread.elf
	riscv32-unknown-elf-objdump --source --all-headers --demangle --line-numbers --wide "rtthread.elf" > "rtthread.lst"

rtthread.siz: rtthread.elf
	riscv32-unknown-elf-size --format=berkeley "rtthread.elf"

# 其他目标
clean:
	-$(RM) $(OBJS)$(SECONDARY_FLASH)$(SECONDARY_LIST)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_DEPS)$(S_UPPER_DEPS)$(C_DEPS) rtthread.elf
	-@echo ' '

secondary-outputs: $(SECONDARY_FLASH) $(SECONDARY_LIST) $(SECONDARY_SIZE)

.PHONY: all clean dependents

-include ../makefile.targets
