################################################################################
# 自动生成的文件。不要编辑！
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_LIST := 
SECONDARY_SIZE := 
ASM_DEPS := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
applications \
board \
libraries/drivers \
libraries/hpm_sdk/components/debug_console \
libraries/hpm_sdk/components/dma_mgr \
libraries/hpm_sdk/drivers/src \
libraries/hpm_sdk/soc/HPM5300/HPM5361/boot \
libraries/hpm_sdk/soc/HPM5300/HPM5361 \
libraries/misc/rtt_interrupt_util \
libraries/misc/rtt_os_tick \
packages/LVGL-v8.3.11/env_support/rt-thread \
packages/LVGL-v8.3.11/src/core \
packages/LVGL-v8.3.11/src/draw/arm2d \
packages/LVGL-v8.3.11/src/draw \
packages/LVGL-v8.3.11/src/draw/nxp/pxp \
packages/LVGL-v8.3.11/src/draw/nxp/vglite \
packages/LVGL-v8.3.11/src/draw/renesas \
packages/LVGL-v8.3.11/src/draw/sdl \
packages/LVGL-v8.3.11/src/draw/stm32_dma2d \
packages/LVGL-v8.3.11/src/draw/sw \
packages/LVGL-v8.3.11/src/draw/swm341_dma2d \
packages/LVGL-v8.3.11/src/extra/layouts/flex \
packages/LVGL-v8.3.11/src/extra/layouts/grid \
packages/LVGL-v8.3.11/src/extra/libs/bmp \
packages/LVGL-v8.3.11/src/extra/libs/ffmpeg \
packages/LVGL-v8.3.11/src/extra/libs/freetype \
packages/LVGL-v8.3.11/src/extra/libs/fsdrv \
packages/LVGL-v8.3.11/src/extra/libs/gif \
packages/LVGL-v8.3.11/src/extra/libs/png \
packages/LVGL-v8.3.11/src/extra/libs/qrcode \
packages/LVGL-v8.3.11/src/extra/libs/rlottie \
packages/LVGL-v8.3.11/src/extra/libs/sjpg \
packages/LVGL-v8.3.11/src/extra/libs/tiny_ttf \
packages/LVGL-v8.3.11/src/extra \
packages/LVGL-v8.3.11/src/extra/others/fragment \
packages/LVGL-v8.3.11/src/extra/others/gridnav \
packages/LVGL-v8.3.11/src/extra/others/ime \
packages/LVGL-v8.3.11/src/extra/others/imgfont \
packages/LVGL-v8.3.11/src/extra/others/monkey \
packages/LVGL-v8.3.11/src/extra/others/msg \
packages/LVGL-v8.3.11/src/extra/others/snapshot \
packages/LVGL-v8.3.11/src/extra/themes/basic \
packages/LVGL-v8.3.11/src/extra/themes/default \
packages/LVGL-v8.3.11/src/extra/themes/mono \
packages/LVGL-v8.3.11/src/extra/widgets/animimg \
packages/LVGL-v8.3.11/src/extra/widgets/calendar \
packages/LVGL-v8.3.11/src/extra/widgets/chart \
packages/LVGL-v8.3.11/src/extra/widgets/colorwheel \
packages/LVGL-v8.3.11/src/extra/widgets/imgbtn \
packages/LVGL-v8.3.11/src/extra/widgets/keyboard \
packages/LVGL-v8.3.11/src/extra/widgets/led \
packages/LVGL-v8.3.11/src/extra/widgets/list \
packages/LVGL-v8.3.11/src/extra/widgets/menu \
packages/LVGL-v8.3.11/src/extra/widgets/meter \
packages/LVGL-v8.3.11/src/extra/widgets/msgbox \
packages/LVGL-v8.3.11/src/extra/widgets/span \
packages/LVGL-v8.3.11/src/extra/widgets/spinbox \
packages/LVGL-v8.3.11/src/extra/widgets/spinner \
packages/LVGL-v8.3.11/src/extra/widgets/tabview \
packages/LVGL-v8.3.11/src/extra/widgets/tileview \
packages/LVGL-v8.3.11/src/extra/widgets/win \
packages/LVGL-v8.3.11/src/font \
packages/LVGL-v8.3.11/src/hal \
packages/LVGL-v8.3.11/src/misc \
packages/LVGL-v8.3.11/src/widgets \
packages/lv_music_demo-v0.3.4/assets \
packages/lv_music_demo-v0.3.4 \
rt-thread/components/drivers/core \
rt-thread/components/drivers/ipc \
rt-thread/components/drivers/misc \
rt-thread/components/drivers/serial \
rt-thread/components/drivers/spi \
rt-thread/components/finsh \
rt-thread/components/libc/compilers/common \
rt-thread/components/libc/compilers/newlib \
rt-thread/libcpu/risc-v/common \
rt-thread/src \
startup/HPM5361 \
startup/HPM5361/toolchains/gcc \

